import 'sentence_realiser.dart';

const aacCards = <CardGrammar>[
  CardGrammar(
    id: 'i_want',
    labelEn: 'I want',
    labelUr: 'چاہتا ہوں',
    pos: PartOfSpeech.carrier,
    isCountable: false,
    startsWithVowelSound: false,
    urduGender: UrduGender.masculine,
    urduSubject: 'میں',
    urduVerbMasculine: 'چاہتا ہوں',
    urduVerbFeminine: 'چاہتی ہوں',
  ),
  CardGrammar(
    id: 'i_feel',
    labelEn: 'I feel',
    labelUr: 'محسوس کرتا ہوں',
    pos: PartOfSpeech.carrier,
    isCountable: false,
    startsWithVowelSound: false,
    urduGender: UrduGender.masculine,
    urduSubject: 'میں',
    urduVerbMasculine: 'ہوں',
    urduVerbFeminine: 'ہوں',
  ),
  CardGrammar(
    id: 'apple',
    labelEn: 'apple',
    labelUr: 'سیب',
    pos: PartOfSpeech.noun,
    isCountable: true,
    startsWithVowelSound: true,
    urduGender: UrduGender.masculine,
  ),
  CardGrammar(
    id: 'water',
    labelEn: 'water',
    labelUr: 'پانی',
    pos: PartOfSpeech.noun,
    isCountable: false,
    startsWithVowelSound: false,
    urduGender: UrduGender.masculine,
  ),
  CardGrammar(
    id: 'happy',
    labelEn: 'happy',
    labelUr: 'خوش',
    pos: PartOfSpeech.adjective,
    isCountable: false,
    startsWithVowelSound: false,
    urduGender: UrduGender.masculine,
  ),
  CardGrammar(
    id: 'help',
    labelEn: 'help',
    labelUr: 'مدد',
    pos: PartOfSpeech.noun,
    isCountable: false,
    startsWithVowelSound: false,
    urduGender: UrduGender.feminine,
  ),
  CardGrammar(
    id: 'finished',
    labelEn: 'finished',
    labelUr: 'ختم',
    pos: PartOfSpeech.adjective,
    isCountable: false,
    startsWithVowelSound: false,
    urduGender: UrduGender.masculine,
  ),
];
