/// The calming ambient sound bed.
///
/// This lives in `sensory_support` rather than beside the AI contracts,
/// which is where it originally sat: it has nothing to do with inference.
/// `ai_contracts.dart` re-exports it so existing imports keep working.
library;

/// One bundled ambient loop.
///
/// All three are generated by `tool/make_ambient_audio.py` under
/// deliberately narrow constraints — no transients, energy below ~1 kHz,
/// seamless loop points, and fades at both file edges. There is no track
/// here with a percussive onset, and there never should be.
enum AmbientTrack {
  softRain('assets/audio/soft_rain.wav'),
  slowOcean('assets/audio/slow_ocean.wav'),
  warmHum('assets/audio/warm_hum.wav');

  const AmbientTrack(this.asset);

  /// Bundled asset path. Local, never streamed — the app is offline-first.
  final String asset;
}

/// Volume policy for the ambient bed.
///
/// The scope calls for a volume ceiling, and this is it. The caregiver's
/// preference is a fraction of a cap, never of full output, so the loudest
/// the app can be is bounded by construction rather than by whoever last
/// dragged the slider.
class AmbientVolumePolicy {
  const AmbientVolumePolicy();

  /// Loudest the bed may ever play in normal mode.
  static const double ceiling = 0.55;

  /// Sensory mode drops the cap considerably further.
  static const double sensoryCeiling = 0.32;

  /// Where a fresh install starts: audible, unobtrusive.
  static const double defaultPreference = 0.6;

  /// Maps a 0..1 caregiver preference onto the active ceiling.
  double resolve({
    required double preference,
    required bool sensoryMode,
  }) {
    final capped = preference.clamp(0.0, 1.0);
    return capped * (sensoryMode ? sensoryCeiling : ceiling);
  }
}

/// Gentle-sound boundary for the calm screen.
///
/// Implementations must keep volume under [AmbientVolumePolicy], never
/// start on their own, and only play after an explicit user action. Looping
/// is allowed once playing — the loops are built to be seamless — but the
/// bed is always off by default on every entry to the screen.
abstract interface class AmbientSoundService {
  bool get isPlaying;

  /// The selected loop. Persisted by the caller, not by the service.
  AmbientTrack get track;

  /// Caregiver preference in 0..1, before the ceiling is applied.
  double get volumePreference;

  Future<void> play();
  Future<void> stop();

  /// Switches loop. Takes effect immediately when already playing.
  Future<void> selectTrack(AmbientTrack track);

  /// Sets the 0..1 preference; the ceiling is applied internally.
  Future<void> setVolumePreference(double value);

  /// Sensory mode lowers the ceiling, so the service needs to know.
  Future<void> setSensoryMode(bool value);

  Future<void> dispose();
}

/// Silent implementation.
///
/// Keeps the toggle honest with no platform audio at all — used in tests,
/// on platforms without an audio output, and as the safe fallback if the
/// player fails to initialise. Behaves exactly like the real service from
/// the caller's point of view; it simply produces no sound.
class SilentAmbientSoundService implements AmbientSoundService {
  SilentAmbientSoundService({
    AmbientTrack track = AmbientTrack.softRain,
    double volumePreference = AmbientVolumePolicy.defaultPreference,
  }) : _track = track,
       _volume = volumePreference;

  bool _playing = false;
  AmbientTrack _track;
  double _volume;

  @override
  bool get isPlaying => _playing;

  @override
  AmbientTrack get track => _track;

  @override
  double get volumePreference => _volume;

  @override
  Future<void> play() async => _playing = true;

  @override
  Future<void> stop() async => _playing = false;

  @override
  Future<void> selectTrack(AmbientTrack track) async => _track = track;

  @override
  Future<void> setVolumePreference(double value) async =>
      _volume = value.clamp(0.0, 1.0);

  @override
  Future<void> setSensoryMode(bool value) async {}

  @override
  Future<void> dispose() async => _playing = false;
}
