// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHuwHlOUvBop67VngaltNBjxXxbdRpMQg',
    appId: '1:394246049460:android:51b455353039e7405a11e1',
    messagingSenderId: '394246049460',
    projectId: 'auth-eb2cf',
    databaseURL: 'https://auth-eb2cf-default-rtdb.firebaseio.com',
    storageBucket: 'auth-eb2cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8KNpwKHcFpthV9UvBWNtVsmNesxJNEgI',
    appId: '1:394246049460:ios:1d33aeb68bcd0d5e5a11e1',
    messagingSenderId: '394246049460',
    projectId: 'auth-eb2cf',
    databaseURL: 'https://auth-eb2cf-default-rtdb.firebaseio.com',
    storageBucket: 'auth-eb2cf.firebasestorage.app',
    iosBundleId: 'com.autimate.autimate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs9Lcgg3qp_tBSRHHtJutTNUebQQMfDEg',
    appId: '1:394246049460:web:09d05c76261baa2d5a11e1',
    messagingSenderId: '394246049460',
    projectId: 'auth-eb2cf',
    authDomain: 'auth-eb2cf.firebaseapp.com',
    databaseURL: 'https://auth-eb2cf-default-rtdb.firebaseio.com',
    storageBucket: 'auth-eb2cf.firebasestorage.app',
  );
}
